site_name: K8sStudies
site_author: Roberto Prevato
site_url: https://robertoprevato.github.io/K8sStudies/
site_description: Personal Kubernetes studies
repo_name: RobertoPrevato/K8sStudies
repo_url: https://github.com/RobertoPrevato/K8sStudies
edit_uri: ""

nav:
  - Overview: index.md
  - Getting started: getting-started.md
  - Kind:
      - Creating a Cluster: kind/creating-a-cluster.md
      - Web Hosting: kind/web-hosting.md
      - Mounting Volumes: kind/mounting-volumes.md
      - Loading Docker Images: kind/loading-docker-images.md
      - Multi Nodes: kind/multi-nodes.md
      - PostgreSQL: kind/postgresql.md
      - CloudNativePG: kind/cloudnativepg.md
  - K3s:
      - Introduction: k3s/index.md
      - Web Hosting: k3s/ingress-per-app.md
      - Monitoring: k3s/monitoring.md
  - Diving deeper:
      - A bit of Docker history: diving-deeper/docker-history.md
  - CHANGELOG: changelog.md

theme:
  features:
    - navigation.footer
    - content.code.copy
    - content.action.view
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  name: "material"
  custom_dir: overrides/
  favicon: img/neoteroi.ico
  logo: img/neoteroi-w.svg
  icon:
    repo: fontawesome/brands/github

validation:
  links:
    absolute_links: ignore

watch:
  - docs
  - overrides

extra:
  header_bg_color: "black"

extra_css:
  - css/neoteroi.css
  - css/extra.css?v=20221120

extra_javascript:
  - js/fullscreen.js

plugins:
  - search
  - glightbox
  - neoteroi.contribs:
      enabled_by_env: "GIT_CONTRIBS_ON" # Use the name you wish here

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      guess_lang: false
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - neoteroi.timeline
  - neoteroi.cards
  - neoteroi.projects
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
