apiVersion: apps/v1
kind: Deployment
metadata:
  name: teal-app
  namespace: teal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teal-app
  template:
    metadata:
      labels:
        app: teal-app
    spec:
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: teal-app
          image: robertoprevato/mvcdemo:latest
          env:
            - name: BG_COLOR
              value: "#008080"
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: teal-app
  namespace: teal
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: teal-app
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teal
  namespace: teal
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - teal.neoteroi.xyz
        - www.teal.neoteroi.xyz
      secretName: teal-neoteroi-xyz-tls
  rules:
    - host: teal.neoteroi.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teal-app
                port:
                  number: 80
    - host: www.teal.neoteroi.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teal-app
                port:
                  number: 80
